//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drive.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class drivingEntities : DbContext
    {
        public drivingEntities()
            : base("name=drivingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Sys_Oper_Log> T_Sys_Oper_Log { get; set; }
        public virtual DbSet<T_Sys_User> T_Sys_User { get; set; }
        public virtual DbSet<T_Sys_Role> T_Sys_Role { get; set; }
    }
}
